### ISSUE TITLE
Reintroduce Log Channel 

### ISSUE THREAD

**Issue by Nanabell** [Frederikam/FredBoat#161]
We have the currently unused log channel in the Hangout and i think it would be a perfect place to have live updates on shard status(es ?)

Thoughts ?

**Comment by Frederikam** [comment]
I would say warnings only. Discord or JDA could spam shard updates, don't want that.

Something like a GC pause would be good to warn about, or a sudden disconnect of many shards at once. Start/shutdown is good too.

**Comment by napstr** [comment]
I've written something the other day that would allow to post to a channel even if the JDA serving the log channel dies, because it uses webhooks.
https://github.com/napstr/logback-discord-appender

I didn't write it with this in mind, it's kinda in a half-assed condition currently, missing a real queue (it is queued, but wont discard anything so spam might happen, webhooks too are rate limited, 5/5s I think), but that can easily be added. We could further adjust it by adding a filter for a keyword to only report those logs we are interested in, instead of all errors as it is currently set.

It's a small addition to make a log channel more robust and reliable.

**Comment by napstr** [comment]
On second thought doing an async call to the webhook from our code directly sounds like the right way to go instead of bothering setting this up. Just copypasta the code to create the webhook request from there.

**Comment by Frederikam** [comment]
Remember that rate limit status is given in the response headers, and that the limits are dynamic.

**Comment by napstr** [comment]
So far I found out that webhooks have a ratelimit of 30 /60s, on top the regular 5/5s channel ratelimit.
I think they are superior to logging through JDA, since we don't need to have a shard up.

There are several way how to tackle this however.

1. Call the webhook directly from our code.
- Pros: Just the webhook pros

2. Write a logback appender, which checks the logs that get written
- Pros: Kinda async
- Cons: Text based analysis of the logs, instead of direct calls

3. Have a script that reads the log file we write.
- Pros: Similar to 2, but resilient to stop the world events or restarts of the application or JVM. A fringe case here would be for example a crash of the application/JVM, where it doesn't recover from. Both 1. and 2. couldn't really detect that as _they wouldn't be running_.
- Cons: Again, text based analysis of what's going on.
