### ISSUE TITLE
Songs lagging

### ISSUE THREAD

**Issue by jhonnymoreira** [Frederikam/FredBoat#246]
It's been a while that my friends and I have been experiencing lag while using FredBoat when playing any kind of song (all from YouTube and SoundCloud). Is it because of a traffic limit imposed from Discord servers? If not, is it possible to end the lag?

In case of features to be added related to this feature, I'm willing to help.

**Comment by Frederikam** [comment]
Are you selfhosting or using the public music bot?

**Comment by Frederikam** [comment]
You're likely dealing with the public bot that we host. Most of the lag is caused by the bandwidth speed at the moment. This is after all pretty close to peak time on a weekend. 

I'm currently working on an application that will allow us to split the audio processing and bandwidth across many nodes, allowing for better scaling: https://github.com/Frederikam/Lavalink 

Discord does not impose a bandwidth limit.

If you want to personally get around the lag you could host your own instance, or get [the patron bot](https://www.patreon.com/fredboat).

**Comment by jhonnymoreira** [comment]
@Frederikam I'm using the public bot, I forgot to specify, sorry. If you can give a briefing to me, I'll be glad to help you. Right now I'm unemployed, so that's the only way I can help [=

**Comment by Frederikam** [comment]
At the moment Lavalink is essentially done, I just need to fix any of the remaining bugs, but they are quite difficult to reproduce. If you're up to that, I can give you a briefing later (when it's not 2 AM for me).

You might be more interested in some of the other open issues we need help with. Most are in need of a developer.

**Comment by jhonnymoreira** [comment]
Let me know a good time for you, I'm at GMT-3. I'm willing to help in those issues (both Lavalink and FredBoat).

Could you ping me on Twitter? Direct Message is easier for me.

https://twitter.com/jhonnymoreira

**Comment by Frederikam** [comment]
Will do after I have slept 👌 

Though the other contributors usually hang out on my Discord server. Ask any admin for the "coder" role to get access to the #coding channel.

https://discord.gg/cgPFW4q
