### ISSUE TITLE
Config option for how info is displayed

### ISSUE THREAD

**Issue by Kurozume** [Frederikam/FredBoat#282]
Make displaying information in embeds available
 - Command Should be `;;config use_embeds <true/false>` or similar
 - Doesn't affect when errors are thrown, they should stay in codeblocks
 - When `use_embeds` is `true`; data should be exported to hastebin for users that have embeds disabled
 - Try to avoid using embed fields with just a title as this creates ugly blank space, if necessary; add the info to the embeds `description` field and surround what would be a field title with `**` to make it bold
 - If possible make it so that there is as little change as possible to existing code
    > Try to make it so the main command method is only executed once, then info is outputted to strings that can either be sent as messages or sent to embeds

I will be looking into this myself at some point, however if someone wishes to look into this themselves feel free, I can provide information on how to set up the config in the database if needed

**Comment by Kurozume** [comment]
As a quick side note:
 - This could even be expanded to `;;config display_style <key>` and would allow for more styles to be implemented quickly if requested in the future.
    > The keys could then be `embed`, `codeblock`, `plaintext` etc

**Comment by napstr** [comment]
> users that have embeds disabled
That's not detectable (not even sure it's a thing). The bot has permissions on a channel / guild scope to show embeds. Bot should display a fat warning if it doesn't get that permission but tries to send an embed (instead of exporting anything).

This sounds like a lot of work (maintaining several formats of _good looking_ output through all messages sent) for questionable benefit (catering to users who don't want to give the bot embed rights). Are there actually users in FredBoats target audience (13yolds) that voluntarily prefer text output over embeds?

**Comment by RealKC** [comment]
This option in the settings disables embeds as well(under Text & Images), but yes it's not detectable so you'd have to send the hastebin link as well as the embed.

![](https://fred.moe/a5v.png)

**Comment by Kurozume** [comment]
That's what I meant
It sends the link all the time if embeds are enabled

**Comment by Macley-Kun** [comment]
@Kurozume why is this closed?

**Comment by Kurozume** [comment]
I closed this because it provides little to zero profit to the public bot and therefore is an unecessary amount of work
However if you wish to add it to your own bot feel free

**Comment by Macley-Kun** [comment]
@Kurozume well idk it depends. Is it just like writing a simple embed as you would do in discord? or do you need actully java knowledge to figure out how to code it? I have no exp in Java or any other language

**Comment by RealKC** [comment]
@Macley-Kun You need knowledge of whatever language you're coding your bot in(in our case Java) to make an embed. Also what do you mean "writing a simple embed as you would do in discord"?

**Comment by Frederikam** [comment]
You need to replace most usages of Message#sendMessage()

AKA a lot of work. Plus having to migrate database schemes. If you have no experience then please don't assume that this is simple.

**Comment by Macley-Kun** [comment]
Wasn't even thinking it would be simple in the first place. That's why i asked if you need exp in java/other language. 

@RealKC i can make embeds in discord as a user with a 'selfbot' you use a command and put some title=<tekst> and description=<tekst>. I just waited for this feature a while and wonderd if i 'could' help.

**Comment by Frederikam** [comment]
>Is it just **like writing a simple embed** as you would do in discord?

Minutes later

>**Wasn't even thinking it would be simple** in the first place. 

😕

**Comment by Macley-Kun** [comment]
I kinda refer simple as in: typing a command in discord simple. Not the actually programming that goes behind is simple.
😭
