### ISSUE TITLE
make Jar version correctly

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#295]
Is it still v1.0???????

**Comment by Kurozume** [comment]
imo maybe 2.0 should be the merging of the bots

**Comment by napstr** [comment]
v1.0.1-SNAPSHOT :^  )

**Comment by knight-ryu12** [comment]
please do that 👍

**Comment by napstr** [comment]
Add build numbers from the CI to the version, and a command line `-v` / `--version` argument outputting the version.

**Comment by Nanabell** [comment]
http://semver.org/ this is my idea of how versioning works but I don't think we do the version stuff. we just needed one release

**Comment by Frederikam** [comment]
Isn't semantic versioning intended for APIs?

**Comment by Nanabell** [comment]
it is yes. but I kinda stuck to it

**Comment by Frederikam** [comment]
The question is just when do we increment major/minor numbers?

**Comment by Nanabell** [comment]
major would be something like the refactor Napster did (implement the CommandContext) or your lavalink
minor in our case would be adding commands or adding small to medium features
and patch ¯\\\_(ツ)_/¯ well it's a patch for a bug
that's my point of view if you think differently spread your knowledge

**Comment by napstr** [comment]
I don't think we need to be too strict with versioning, since, as Fred mentioned, this is not an API, FredBoat is not intended to be a dependency. Just bump the version when you feel like it imo. Merging into master is a great place to think about bumping it. For our internal use build numbers and git hashes are good enough :tm:
