### ISSUE TITLE
Update Selfhosting with Heroku

### ISSUE THREAD

**Issue by Macley-Kun** [Frederikam/FredBoat#325]
So i have bin working on getting FredBoat working on Heroku, and eventually got it to work.
I'm testing it for 5-6 days now, and overall it never got any lags. Sometimes very little but that could be on my side.

I made an instruction that can be added to the selfhosting section of FredBoat.

[Hosting FredBoat in Heroku.docx](https://github.com/Frederikam/FredBoat/files/1346746/Hosting.FredBoat.in.Heroku.docx)

If you have any questions about the hosting in Heroku feel free to ask. Take in consideration that i'm not a programmer nor have much experience using Heroku.

**Comment by napstr** [comment]
Can you please write that document as markdown? Easiest way to do that is to create a [gist](https://gist.github.com/).

**Comment by Shredder121** [comment]
Also, we're already in a git directory that you can push to heroku.
I don't think you need to `git init` _again_ and hoist the FredBoat folder out to its own repo.
Updating then is not possible I think?

**Comment by Macley-Kun** [comment]
@napstr allright i made it into gist for ya, here's the link: https://gist.github.com/Macley-Kun/c04ac6f0d205cb416f9fc248d2b86e32

@Shredder121 You can actually update it, i assume you just re-clone the FredBoat Github, and then you can follow these steps:
git add .
git commit -am "make it better"
git push heroku master

I used git init because Heroku itself described in the deployment part. It worked for me so i just went with it.

**Comment by napstr** [comment]
> Can you please write that document as markdown?
This hasn't happened yet.

**Comment by Macley-Kun** [comment]
@napstr sorry updated it in markdown :P

**Comment by napstr** [comment]
Still not markdown. Here is an example of a gist formatted in markdown: https://gist.github.com/napstr/0fc7ef5cc3e7fe9f3a27b320b03a008d

**Comment by Macley-Kun** [comment]
I updated it to the markdown this time XP Can you give me some suggestions on how it looks?

**Comment by Shredder121** [comment]
> @Shredder121 You can actually update it, i assume you just re-clone the FredBoat Github, and then you can follow these steps:
> git add .
> git commit -am "make it better"
> git push heroku master

You don't.
Heroku acts like a remote, so you add the remote to the existing git repository.
You do not make a new one, splitting the repo up in 2 repos.

**Comment by Macley-Kun** [comment]
Allright i'll remove the git init part then. Because it's not needed :-)

**Comment by napstr** [comment]
> Can you give me some suggestions on how it looks?

I think you are trolling at this point. The document is still not markdown. I'm going to unsubscribe from this issue.

**Comment by Macley-Kun** [comment]
Um i'm not trying to troll? I even pasted the content into a online markdown and it showed me the same look as on the FredBoat site?
What would benefit me to troll you? I just wanted to share the way i got FredBoat hosted into Heroku. That's all

**Comment by napstr** [comment]
You were asked three times for the same, simple thing, and all these times you claimed that you fullfilled it, but even after spoon feeding you a perfect example of how a formatted file looks like you still actually haven't. I personally for myself will not accept that maintaining the possible future maintainer of a guide takes up so much time and effort. You were told from the start that if you want to have this edge case guide be part of the project, you need to step up and take responsibility and make an effort to do things correctly by yourself, since none of the existing contributors is using or planning to use Heroku, yet we will have to deal with users following the guide, so a high quality and a promise to maintain it in the future are key to it. From my point of view you failed at minimizing this friction even before we actually reached the point of looking at the guide, which I can't call anything different but an elaborate attempt at trolling. So I made a decision for my own sake. Please note that this is a personal decision of just me, Napster. Feel free to talk to any other collaborateur about this issue.
Rather than silently ignoring this github issue (which would undoubtedly cause frustration on your side), I am taking my time right now to try to communicate my point of view clearly and openly of why I am unsubscribing. I think this gives every participant the best chance to grow and paves the way for successful collaboration in the future.

**Comment by Macley-Kun** [comment]
[Instruction how to host FredBoat in Heroku 8okt 2017.docx](https://github.com/Frederikam/FredBoat/files/1366931/Instruction.how.to.host.FredBoat.in.Heroku.8okt.2017.docx)
If you just so happen to find this issue, you can use this instruction. Don't ping me if you don't know how to use it/fix the errors. Don't ask the FredBoat developers/staff if you use this methode.

PS. All steps are indeed neccessary including git init because you would be one commit ahead error.
PPS. If your smart, you compile the bot locally, test it and if your got errors then ask about it. The chances that you still get errors in Heroku will be significant less.

**Comment by Wakjyst** [comment]
help please
remote:        [ERROR] Plugin org.apache.maven.plugins:git-commit-id-plugin:2.2.3 or one of its dependencies could not be resolved: Could not find artifact org.apache.maven.plugins:git-commit-id-plugin:jar:2.2.3 in central (https://repo.maven.apache.org/maven2) -> [Help 1]

**Comment by Kurozume** [comment]
Why has this been posted here, we have a channel in the server which you can post your issue in and we can help you resolve it.
Check out the #selfhosters channel in FredBoat Hangout
https://discord.gg/vC44uFW
