### ISSUE TITLE
[Discussion] Should we migrate the i13n repo to this one?

### ISSUE THREAD

**Issue by Frederikam** [Frederikam/FredBoat#335]
I fear that our current system adds too much [unnecessary complexity](https://github.com/Frederikam/FredBoat/blob/master/CONTRIBUTING.md#translations-1) in the PR process.

Should we migrate the i18n files to this repo? How would we go about it?

Also, how do we go about missing translations in the non-en_US locales?
* Do we fail the build?
* Do we automatically fall back to en_US and avoid failing the build?
* Do we write a program that copies over the untranslated strings from en_US as part of the build process?

**Comment by Nanabell** [comment]
I ask this again is this now fukin I18n or I13n ? Ree

**Comment by Frederikam** [comment]
It's called i13n but it should be i18n. i13n is broader, but what we are doing is just i18n.

**Comment by napstr** [comment]
I agree, while I do have a solid grasp of the process now, it is still a minor nuisance to go through it each time, and is especially confusing to new contributors. Syncing the git module is also annoying.

Failing the build because translations are missing is only needed if we can't handle it gracefully.
I have a i18n refactor PR coming up that is adding i18n convenience methods to the Context that would make it easy to fall back to the DEFAULT language pack if a resource key is missing, so I would prefer doing that instead of some script that copies over stuff (crowdin does that us already each time we make a build).

**Comment by Frederikam** [comment]
Let's split this issue in two:
- [ ] Gracefully fall back to en_US strings when a string is not found in a different locale
- [ ] Migrate the I13n repo to this one

**Comment by napstr** [comment]
Here's the solution for the first one: https://github.com/Frederikam/FredBoat/pull/337/commits/9c993efc0108510dedcb247f9db9c663edffabea

**Comment by napstr** [comment]
Migration: c28d08a2cc0945016992258d07503b43ec5ae473
- [ ] Update CONTRIBUTING.md

**Comment by napstr** [comment]
All done.
