### ISSUE TITLE
command output changing opinions

### ISSUE THREAD

**Issue by knight-ryu12** [Frederikam/FredBoat#389]
I need opinion about changing some of output.
`Known servers: ` in ;;stats, I think it should be `Known guilds:`

What's your opinion about changing servers to guilds. 

EDIT:
Discord API called Server as `Guild`.
Since this is sort-of debug command, I think using `Guild` is good.
But Discord UI/X call `Guild` as `Server`.
So, I think using `Guild` is suitable for debug output.

**Comment by napstr** [comment]
I don't think it is worth discussing the guilds vs servers naming conventions for a command that is meant for end users.

There could be a general discussion had about which word to use bot-wide. Your original post is missing the reason why you think one thing should be preferred over the other, so please add that, otherwise I don't know how this would lead to a constructive discussion. If it's just about voicing an opinion, a straw poll would be a better tool.

**Comment by knight-ryu12** [comment]
Edited. I added my opinion about it.
