### ISSUE TITLE
;;perms command

### ISSUE THREAD

**Issue by TheLMiffy1111** [Frederikam/FredBoat#41]
Makes certain commands available only to certain user groups.

**Comment by RealKC** [comment]
The Dashboard(#23) will allow you to choose which roles will be able to use certain commands.

**Comment by Frederikam** [comment]
How would usage be like?

**Comment by Nanabell** [comment]
i would assume ;;perms <Command> <MinRole> 
and minRole is bound to the Discord hierarchy (Position)

**Comment by Frederikam** [comment]
I kinda don't like the idea of using command names as keys, since aliases are a thing and some commands do similar things (such as ;;fwd, ;;rew, ;;restart and ;;seek)

Instead, we might want to have groups of permissions. Or both.

Ultimately I would prefer a system that is as close to Discord's system as possible. UI design for the dashboard should also be considered.

**Comment by napstr** [comment]
Duplicate of https://github.com/Frederikam/FredBoat/issues/198
