### ISSUE TITLE
Support for picosong

### ISSUE THREAD

**Issue by auburnete** [Frederikam/FredBoat#487]
[picosong](http://picosong.com/) is an audio upload service, allowing users to upload MP3 files and get a quick playback link. I think this might be a good way of allowing arbitrary MP3 files to be played while still avoiding DDOS problems: picosong has a limit of 15MB for uploaded MP3 files, and it shouldn't reveal the IP address of FredBoat either.

picosong URLs look like this: `http://picosong.com/weFyM/`. A link to the .mp3 file can be obtained by going to `http://picosong.com/download/weFyM/` and scraping that webpage for the link to the .mp3 file. (It's inside a div called `.download-link`.)

There are a bunch of other 'quick audio sharing' sites, but I felt that picosong has a good balance between being relatively simple to extract the .mp3 file while not being completely unknown and suspicious. 

Would this be something that would be possible and/or improve FredBoat? Thanks.

**Comment by shikhir-arora** [comment]
I can't speak for whether it would be good for FredBoat, but requests like this should be submitted to: https://github.com/sedmelluq/lavaplayer if you're wanting it as a supported source natively. But keep in mind unless there's a lot of popularity around this you would likely have to submit a PR yourself.

I think FredBoat's traffic is 95+% YouTube, so I'm not sure if it would be worth implementing.

Also, the way it's setup now would require a few changes if it's just FredBoat because it's just an HTTP URL - so as it is now it would require exposing that. Of course if it was very popular (I'm not too sure if it is) then it can be done, but that's my $0.02.

**Comment by Frederikam** [comment]
While we *could* add support for this ourselves, it would be much more convenient if support was added upstream in Lavaplayer first.
