### ISSUE TITLE
Suggestion: support for http://remix.kwed.org/

### ISSUE THREAD

**Issue by Natherul** [Frederikam/FredBoat#513]
Would it be possible to support playback from http://remix.kwed.org/
?

**Comment by napstr** [comment]
It is already supported.
![image](https://user-images.githubusercontent.com/6048348/42960820-40dc4644-8b8d-11e8-9e5c-93bddc616ffb.png)

**Comment by Natherul** [comment]
![image](https://user-images.githubusercontent.com/3688166/42961351-de0e8caa-8b8e-11e8-92c2-c3d27c2e20d8.png)

Not getting it to work, is it a patron only feature? Because I cant seem to find any info about that in  https://fredboat.com/docs#music-commands
more than that its been disabled over HTTP(S)

**Comment by Raven-Rose** [comment]
HTTP audio sources are currently disabled on the Non-Patron bot due to vulnerabilites, so for the moment this is a patron only feature, yes. If you would like to have this specific site supported you would need to get it supported on [Lavaplayer](https://github.com/sedmelluq/lavaplayer), either through opening an issue requesting support or by making a pull request that adds support for the site.

**Comment by Natherul** [comment]
ah, than its a case that I find the page unclear :D thanks for the information
