### ISSUE TITLE
Playing Spotify tracks/playlists as Youtube tracks

### ISSUE THREAD

**Issue by Disputes** [Frederikam/FredBoat#74]
https://github.com/adhorrig/spodl (very active. javascript) idk if its harder to code between two languages so here are two java based one 
https://github.com/nyxaria/Spotify-to-MP3(idk but its java, couldn't compile as its got no pom.xml for maven)
https://github.com/mlkmn/spotify-downloader(another java older and might not work but i can compile it)

found this while on reddit finding the Spotify premium mod for a friend. seems interesting, 

would it be possible to add this to the bot so it can read spotify links and then find and play it from youtube? thus bypassing the strict steaming rules of spotify

**Comment by Frederikam** [comment]
This could be a thing, though it currently isn't very high on my list and I'm already really busy.

Contributions welcome.

**Comment by napstr** [comment]
Been working on this and basically it's in a functioning state. There is a problem though, the only decent [Java Spotify API](https://github.com/thelinmichael/spotify-web-api-java) I found is a bit dated, and one of the things it's missing is loading more than the first page of a playlist, so currently it works only for the first 100 tracks.

For me it would mean a non-trivial amount of work to go and fix this, because it sounds like lots of stuff I haven't done yet (inb4 I'm just panicking and actually fix it in a day's time lol).

I see several paths to fix this:
- Ditch that Spotify API and do our own few requests. For the Spotify playlist feature we need authorization + 2 kinds of requests, that's not too complicated.
- Keep that Spotify API, somehow make the missing request from scratch in our own code
- Fork the Spotify API, add the missing request, and publish it

I think adding and keeping the Spotify API in FredBoat would be worth it, because chances are high (this is a MusicBot, after all) we might want to do even more requests to Spotify in the future.

I feel like going with option two, and then later, if I can be assed, to do it the correct way which is option 3.


I'm planning to polish what I currently have (= only add first 100 tracks of Spotify playlists), and then go do the fix for that underlying issue.

Feel free to chip in thoughts on what to do, and whether FredBoat would want to roll out limited Spotify playlist support first and then upgrade later, or do the full thing later.

**Comment by Frederikam** [comment]
Either path works for me. I would imagine that it would be pretty simple to just fetch the full list with just a loop of REST requests in the source manager.

API documentaion:
https://developer.spotify.com/web-api/get-playlists-tracks/

**Comment by napstr** [comment]
In case you were wondering how I solved the aforementioned thing: After going on a small odyssey including using java reflection to access private methods and other nonsense I settled with the 4th option of utilizing my brain correctly and using that Spotify API properly (turned out I just needed to add parameters to its requests).

**Comment by Disputes** [comment]
just to add to this. its also possible to request single tracks and albums. ive done it discord python bot so i could see if i can work it out for java

**Comment by napstr** [comment]
Indeed. Could be a convenient way to access information on artists/albums/other stuff to create playlists which are then loaded over music providers.
https://developer.spotify.com/web-api/search-item/

**Comment by Frederikam** [comment]
This is now available on the `development` branch for selfhosted bots and the patron bot. Thanks napstr!
